version: '3.9'

services:
  backend:
    depends_on:
      - postgresdb
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    networks:
      - db-net
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    links:
      - backend
    
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    networks:
      - db-net

  postgresdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    env_file:
      - backend/.env
    networks:
      - db-net

volumes:
  postgresdb_data:

